-- Create customers table to store customer information
CREATE TABLE public.customers (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  whatsapp_number TEXT UNIQUE NOT NULL,
  name TEXT,
  phone TEXT,
  location TEXT,
  product_interest TEXT,
  is_lead BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  last_interaction TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security (RLS) for the customers table
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow full access for backend services (service_role)
CREATE POLICY "Allow service role full access on customers"
ON public.customers
FOR ALL
USING (auth.role() = 'service_role')
WITH CHECK (auth.role() = 'service_role');

-- Create conversations table to log interactions
CREATE TABLE public.conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  whatsapp_number TEXT NOT NULL,
  message_text TEXT,
  ai_response_text TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS for the conversations table
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow full access for backend services (service_role)
CREATE POLICY "Allow service role full access on conversations"
ON public.conversations
FOR ALL
USING (auth.role() = 'service_role')
WITH CHECK (auth.role() = 'service_role');