// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://lvjhukyqybdcvbhwqxqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2amh1a3lxeWJkY3ZiaHdxeHFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NjIwODYsImV4cCI6MjA3MDMzODA4Nn0.43xHI1Errpzw0so8YeUzK-tjC6-Zq1dG3s1ItXJ3ZuE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);